const info = {
    me: 'òbàdàfídì',
    url: 'https://www.obadafidi.tech',
    shortcutIcon: 'icon.svg',
    github: 'https://github.com/obadafidii',
    email: 'davidtofunmidada@gmail.com',
    socials: {
        twitter: 'https://x.com/obadafidiii',
        linkedin: 'https://linkedin.com/in/obadafidi',
    },
    navLinks: [
        { title: 'home', href: '/' },
        { title: 'works', href: '/works' },
        { title: 'blog', href: '/blog' },
        { title: 'resume', href: '/resume' },
        { title: 'contact', href: '/contact' },
    ],
    works: [
        {
            name: 'Terrace',
            file: 'terrace',
            kind: 'product' as const,
            url: 'https://app.terrace.fi/i',
            description: 'CEX and DEX pool aggregator',
            tags: ['go', 'solana', 'kubernetes', 'timescaledb', 'neo4j', 'crypto'],
        },
        {
            name: 'Curaboard',
            file: 'curaboard',
            kind: 'product' as const,
            url: 'https://www.curaboard.com/',
            description: 'A single home for all your shopping finds',
            tags: ['nodejs', 'postgres', 'aws', 'dns', 'tls'],
        },
        {
            name: 'Groove',
            file: 'groove',
            kind: 'product' as const,
            url: 'https://groove.ng/',
            description: 'Music and video streaming platform',
            tags: ['nodejs', 'postgres', 'mongo', 's3', 'eks', 'gcp', 'stripe'],
        },
        {
            name: 'Minired',
            file: 'minired',
            kind: 'build' as const,
            url: 'https://github.com/tdadadavid/minired',
            description: 'Redis core functionality implemented in Go from scratch',
            tags: ['go', 'database', 'backend'],
        },
        {
            name: 'Orchestra',
            file: 'orchestra',
            kind: 'build' as const,
            url: 'https://github.com/tdadadavid/orchestra',
            description: 'Lightweight task orchestration, coordinating workers in Go',
            tags: ['go', 'backend'],
        },
        {
            name: 'DNS',
            file: 'go-dns',
            kind: 'build' as const,
            url: 'https://github.com/tdadadavid/go-dns',
            description: 'Domain name server in Go, written after the AWS DNS outage',
            tags: ['go', 'dns', 'backend'],
        },
        {
            name: 'Search Engine',
            file: 'search-engine',
            kind: 'build' as const,
            url: 'https://github.com/tdadadavid/search-engine',
            description: 'Search engine in C#, built for performance and reliability',
            tags: ['c#', 'algorithms', 'backend'],
        },
        {
            name: 'Web Analytics',
            file: 'web-analytics',
            kind: 'build' as const,
            url: 'https://github.com/tdadadavid/google-analytics',
            description: 'Tracks page visits, user locations and device usage',
            tags: ['javascript', 'analytics', 'cli'],
        },
        {
            name: 'Slide Scribe',
            file: 'slide-scribe',
            kind: 'build' as const,
            url: 'https://github.com/tdadadavid/SlideScribeAI-Backend',
            description: 'Hackathon backend for transcribing and processing slides',
            tags: ['typescript', 'backend', 'hackathon'],
        },
    ],
};

export default info;
